### PR TITLE
Support ESXi 7.0 by ignoring 32-bit libvmkctl when it's not present

### PR DESCRIPTION
**Pull request by shanyungyang**

### CODE REVIEW

**Comment by ilovepancakes95** [comment]
@shanyungyang @hugepants Install goes successful for me but after rebooting, SMC Test fails by returning "smcPresent = false". Any ideas? This is on ESXi 7.0.

**Comment by m-sopython** [comment]
Doesn't work on ESXi 7.0 
File unlocker.tgz does not exist
Pls help me

**Comment by m-sopython** [comment]
I have the same thing on ESXi 7.0, but successfully after reboot it gives "smcPresent = false"

**Comment by ilovepancakes95** [comment]
@m-sopython 

> I have the same thing on ESXi 7.0, but successfully after reboot it gives "smcPresent = false"

When I first tried installing, it added unlocker.tgz to the /altbootbank so after I rebooted, unlocker didn't work, I installed it again and this time it added to /bootbank and after rebooting that second time, it worked. So maybe try installing twice with a reboot in between, and then after 2nd time, reboot again, wait 10 minutes even after system is completely up, then try SMC test script. I get a successful result then.

**Comment by m-sopython** [comment]
ESXi host stopped loading, gives an error "Failed to mount boot tardisks"

**Comment by ilovepancakes95** [comment]
And all you did is run the install script twice with a reboot in between? I have no idea what would cause that, the script seems to just add unlocker.tgz to the bootbanks and adds that module to boot.cfg. You can try removing unlocker.tgz from boot.cfg to see if it boots again, or try the command in readme to disable unlocker when booting up ESXi with boot flags.

**Pull request merged**
